---
- hosts: localhost
  become_user: ubuntu
  gather_facts: false 
  tasks:
    - name: Login to docker registry
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"
        registry_url : "{{ DOCKER_REPO_DOMAIN }}"
      register: login_info 

    - name: building the strapi image
      docker_image:
        build:
          path: "{{ PROJECT_PATH }}"
        name: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
        repository: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_IMAGE_NAME }}"
        push: yes
        state: present
        source: build
        register: build_info 

    - name: building the strapi image
      docker_image:
        build:
          path: "{{ PROJECT_PATH_VAL }}"
          dockerfile: "{{ PROJECT_DOCKERFILE | default('Dockerfile') }}"
        source: build
        tag: latest
        # name: "{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
        name: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
        repository: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_IMAGE_NAME }}"
        # push: true
      register: buildLog

    # - name: manual docker push
    #   become_user: ubuntu
    #   shell: docker push "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
    #   register: build_info 

    - debug : 
        var : login_info

    - debug : 
        var : build_info



    #     # cloud.canister.io:5000/lusamreth/polymer-strapi-cms
    # - name: pruning the image
    #   docker_build:
    #     name: "{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
    #     state: absent
    #     tag: latest
