---
- hosts: localhost
  become_user: ubuntu
  gather_facts: false 
  tasks:
    - name: Login to docker registry
      docker_login:
        username: "{{ DOCKER_USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"
        registry_url : "{{ DOCKER_REPO_DOMAIN }}"
      register: login_info 

    - name: building the target image
      docker_image:
        build:
          path: "{{ PROJECT_PATH_VAL }}"
          dockerfile: "{{ PROJECT_DOCKERFILE | default('Dockerfile') }}"
        source: build
        tag: latest
        # name: "{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
        name: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
        repository: "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_IMAGE_NAME }}"
        # push: true
      register: buildLog

    - name: manual docker push
      become_user: ubuntu
      shell: docker push "{{ DOCKER_REPO_DOMAIN }}/{{ DOCKER_USERNAME }}/{{ DOCKER_IMAGE_NAME }}"
      register: build_info 

    - debug : 
        var : login_info

    - debug : 
        var : build_info

